# Generated by Django 6.0.5 on 2026-05-08 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('rows_loaded', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('error_msg', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BattingSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(db_index=True)),
                ('stint', models.SmallIntegerField(default=1)),
                ('team', models.CharField(max_length=4)),
                ('league', models.CharField(max_length=2, null=True)),
                ('games', models.SmallIntegerField(null=True)),
                ('plate_appearances', models.IntegerField(null=True)),
                ('at_bats', models.IntegerField(null=True)),
                ('runs', models.SmallIntegerField(null=True)),
                ('hits', models.SmallIntegerField(null=True)),
                ('doubles', models.SmallIntegerField(null=True)),
                ('triples', models.SmallIntegerField(null=True)),
                ('home_runs', models.SmallIntegerField(null=True)),
                ('rbi', models.SmallIntegerField(null=True)),
                ('stolen_bases', models.SmallIntegerField(null=True)),
                ('caught_stealing', models.SmallIntegerField(null=True)),
                ('walks', models.SmallIntegerField(null=True)),
                ('strikeouts', models.SmallIntegerField(null=True)),
                ('ibb', models.SmallIntegerField(null=True)),
                ('hbp', models.SmallIntegerField(null=True)),
                ('sacrifice_hits', models.SmallIntegerField(null=True)),
                ('sacrifice_flies', models.SmallIntegerField(null=True)),
                ('gidp', models.SmallIntegerField(null=True)),
                ('total_bases', models.SmallIntegerField(null=True)),
                ('batting_avg', models.FloatField(null=True)),
                ('on_base_pct', models.FloatField(null=True)),
                ('slugging_pct', models.FloatField(null=True)),
                ('ops', models.FloatField(null=True)),
                ('ops_plus', models.SmallIntegerField(null=True)),
                ('war', models.FloatField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_seasons', to='players.player')),
            ],
            options={
                'indexes': [models.Index(fields=['year'], name='stats_batti_year_5e4ace_idx'), models.Index(fields=['player', 'year'], name='stats_batti_player__0858b7_idx')],
                'unique_together': {('player', 'year', 'stint', 'team')},
            },
        ),
        migrations.CreateModel(
            name='PitchingSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(db_index=True)),
                ('stint', models.SmallIntegerField(default=1)),
                ('team', models.CharField(max_length=4)),
                ('league', models.CharField(max_length=2, null=True)),
                ('wins', models.SmallIntegerField(null=True)),
                ('losses', models.SmallIntegerField(null=True)),
                ('games', models.SmallIntegerField(null=True)),
                ('games_started', models.SmallIntegerField(null=True)),
                ('complete_games', models.SmallIntegerField(null=True)),
                ('sho', models.SmallIntegerField(null=True)),
                ('saves', models.SmallIntegerField(null=True)),
                ('games_finished', models.SmallIntegerField(null=True)),
                ('ip_outs', models.IntegerField(null=True)),
                ('hits_allowed', models.SmallIntegerField(null=True)),
                ('runs_allowed', models.SmallIntegerField(null=True)),
                ('earned_runs', models.SmallIntegerField(null=True)),
                ('home_runs', models.SmallIntegerField(null=True)),
                ('walks', models.SmallIntegerField(null=True)),
                ('ibb', models.SmallIntegerField(null=True)),
                ('strikeouts', models.SmallIntegerField(null=True)),
                ('hbp', models.SmallIntegerField(null=True)),
                ('wild_pitches', models.SmallIntegerField(null=True)),
                ('balks', models.SmallIntegerField(null=True)),
                ('bfp', models.IntegerField(null=True)),
                ('sacrifice_flies', models.SmallIntegerField(null=True)),
                ('gidp', models.SmallIntegerField(null=True)),
                ('era', models.FloatField(null=True)),
                ('era_plus', models.SmallIntegerField(null=True)),
                ('fip', models.FloatField(null=True)),
                ('whip', models.FloatField(null=True)),
                ('hits_per_nine', models.FloatField(null=True)),
                ('home_runs_per_nine', models.FloatField(null=True)),
                ('walks_per_nine', models.FloatField(null=True)),
                ('strikeouts_per_nine', models.FloatField(null=True)),
                ('strikeouts_per_walk', models.FloatField(null=True)),
                ('war', models.FloatField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitching_seasons', to='players.player')),
            ],
            options={
                'indexes': [models.Index(fields=['year'], name='stats_pitch_year_25c8f9_idx'), models.Index(fields=['player', 'year'], name='stats_pitch_player__cb10c3_idx')],
                'unique_together': {('player', 'year', 'stint', 'team')},
            },
        ),
    ]
