# Generated by Django 6.0.5 on 2026-05-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battingseason',
            name='league',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='pitchingseason',
            name='league',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
