# Generated by Django 6.0.5 on 2026-05-10 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_asg_first_player_asg_games_player_asg_last'),
        ('stats', '0002_alter_battingseason_league_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('kind', models.CharField(choices=[('mvp', 'Most Valuable Player'), ('cy', 'Cy Young Award'), ('roty', 'Rookie of the Year'), ('gg', 'Gold Glove'), ('ss', 'Silver Slugger'), ('tc_b', 'Triple Crown (Batting)'), ('tc_p', 'Triple Crown (Pitching)'), ('hof', 'Hall of Fame'), ('postmvp', 'Postseason MVP'), ('bat_title', 'Batting Title'), ('era_title', 'ERA Title'), ('all_mlb', 'All-MLB Team'), ('ws', 'World Series Champion')], max_length=12)),
                ('league', models.CharField(blank=True, max_length=3, null=True)),
                ('notes', models.CharField(blank=True, max_length=50, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='players.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player', 'year'], name='stats_playe_player__973e27_idx')],
                'unique_together': {('player', 'year', 'kind', 'league')},
            },
        ),
    ]
