# Generated by Django 6.0.5 on 2026-05-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_playeraward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeraward',
            name='kind',
            field=models.CharField(choices=[('mvp', 'Most Valuable Player'), ('cy', 'Cy Young Award'), ('roty', 'Rookie of the Year'), ('gg', 'Gold Glove'), ('ss', 'Silver Slugger'), ('tc_b', 'Triple Crown (Batting)'), ('tc_p', 'Triple Crown (Pitching)'), ('hof', 'Hall of Fame'), ('postmvp', 'Postseason MVP'), ('bat_title', 'Batting Title'), ('era_title', 'ERA Title'), ('all_mlb', 'All-MLB Team'), ('ws', 'World Series Champion'), ('asg', 'All-Star Game')], max_length=12),
        ),
    ]
