# Generated by Django 6.0.5 on 2026-05-10 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_remove_player_asg_first_remove_player_asg_games_and_more'),
        ('stats', '0004_add_asg_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatcastZoneBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('B', 'Batter'), ('P', 'Pitcher')], max_length=1)),
                ('outcome', models.CharField(choices=[('contact', 'Contact'), ('hits', 'Hits'), ('whiffs', 'Whiffs')], max_length=10)),
                ('plate_x', models.FloatField()),
                ('plate_z', models.FloatField()),
                ('count', models.IntegerField()),
                ('total', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_buckets', to='players.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player', 'role', 'outcome'], name='stats_statc_player__df4a0c_idx')],
                'unique_together': {('player', 'role', 'outcome', 'plate_x', 'plate_z')},
            },
        ),
    ]
