# Generated by Django 6.0.5 on 2026-05-13 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_primary_position'),
        ('stats', '0006_fieldingseason_fieldingpositiontoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='JamesScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_ink_bat', models.SmallIntegerField(default=0)),
                ('gray_ink_bat', models.SmallIntegerField(default=0)),
                ('hof_monitor_bat', models.SmallIntegerField(default=0)),
                ('black_ink_pit', models.SmallIntegerField(default=0)),
                ('gray_ink_pit', models.SmallIntegerField(default=0)),
                ('hof_monitor_pit', models.SmallIntegerField(default=0)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='james_score', to='players.player')),
            ],
        ),
    ]
