# Generated by Django 6.0.5 on 2026-05-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('bbref_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mlbam_id', models.IntegerField(db_index=True, null=True, unique=True)),
                ('fangraphs_id', models.IntegerField(db_index=True, null=True)),
                ('retro_id', models.CharField(max_length=20, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_year', models.SmallIntegerField(null=True)),
                ('birth_country', models.CharField(max_length=100, null=True)),
                ('bats', models.CharField(max_length=1, null=True)),
                ('throws', models.CharField(max_length=1, null=True)),
                ('debut', models.DateField(null=True)),
                ('final_game', models.DateField(null=True)),
                ('mlb_played_first', models.SmallIntegerField(null=True)),
                ('mlb_played_last', models.SmallIntegerField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='players_pla_last_na_1786cf_idx'), models.Index(fields=['mlb_played_first', 'mlb_played_last'], name='players_pla_mlb_pla_4c097b_idx')],
            },
        ),
    ]
