# Generated by Django 6.0.5 on 2026-05-10 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_asg_first_player_asg_games_player_asg_last'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='asg_first',
        ),
        migrations.RemoveField(
            model_name='player',
            name='asg_games',
        ),
        migrations.RemoveField(
            model_name='player',
            name='asg_last',
        ),
    ]
