# Generated by Django 6.0.5 on 2026-05-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_remove_player_asg_first_remove_player_asg_games_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='player',
            name='players_pla_mlb_pla_4c097b_idx',
        ),
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['debut', 'final_game'], name='players_pla_debut_47427a_idx'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='player',
            name='mlb_played_first',
        ),
        migrations.RemoveField(
            model_name='player',
            name='mlb_played_last',
        ),
    ]
