# Generated by Django 6.0.5 on 2026-05-31 20:13

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_primary_position'),
    ]

    operations = [
        VectorExtension(),  # CREATE EXTENSION IF NOT EXISTS vector
        migrations.CreateModel(
            name='MethodologyChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=120)),
                ('chunk_index', models.SmallIntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='players_met_slug_ce03b3_idx')],
                'unique_together': {('slug', 'chunk_index')},
            },
        ),
    ]
