# Generated by Django 6.0.5 on 2026-05-31 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_methodologychunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerNarrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('source', models.CharField(max_length=12)),
                ('model', models.CharField(blank=True, max_length=60, null=True)),
                ('flagged', models.JSONField(default=list)),
                ('trace', models.JSONField(default=dict)),
                ('data_version', models.CharField(blank=True, max_length=20, null=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='narrative', to='players.player')),
            ],
        ),
    ]
