import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

# Load a local .env (gitignored) for dev. No-op in production, where Railway
# injects real environment variables directly.
load_dotenv(BASE_DIR / '.env')

# --- Core ---

SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-jnyn@30==_&q&%n*_*-!&!t=&cfw=par=(g^#lhpx)gwqc*hna',
)

DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if h.strip()
] + ['healthcheck.railway.app']

# --- Apps ---

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'players',
    'stats',
]

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pca_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pca_backend.wsgi.application'

# --- Database ---

_db_url = os.environ.get('DATABASE_URL') or 'postgres://connorslakey@localhost:5432/pca_v2'
DATABASES = {
    'default': dj_database_url.parse(_db_url, conn_max_age=600, conn_health_checks=True)
}

# --- Password validation ---

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- Internationalisation ---

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --- Static files ---
# Django admin assets → collected into staticfiles/ → served at /static/
# React SPA bundle   → read from frontend/dist/    → served at / via whitenoise root

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

# Serve the built React SPA at the root URL (alongside /static/ and /api/)
WHITENOISE_ROOT = BASE_DIR / 'frontend' / 'dist'
WHITENOISE_INDEX_FILE = True

# --- CORS (dev only — same-origin in production) ---

CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.environ.get(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:5173,http://127.0.0.1:5173',
    ).split(',')
    if o.strip()
]

# --- CSRF ---

CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if o.strip()
]

# --- Production security (only when DEBUG is off) ---

if not DEBUG:
    # Railway terminates TLS at the edge and forwards plain HTTP internally,
    # so SECURE_SSL_REDIRECT must be off — the redirect happens at the proxy.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# --- LLM (grounded narrative feature) ---
# Feature degrades gracefully: with no key, narrative endpoints serve the
# deterministic template and nothing touches the Anthropic SDK.

ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
NARRATIVE_MODEL = os.environ.get('NARRATIVE_MODEL', 'claude-haiku-4-5-20251001')
LLM_ENABLED = bool(ANTHROPIC_API_KEY)
# When true (default), the narrative is generated by a tool-calling agent that
# fetches its own facts; when false, the model gets the full facts in one shot.
NARRATIVE_USE_TOOLS = os.environ.get('NARRATIVE_USE_TOOLS', 'true').lower() == 'true'
# When true, the agent must submit its draft through the `submit_summary` tool
# with a typed binding for every number, and each number is verified against its
# *named* stat (closes the cross-stat collision the flat verifier waves through).
# Off by default: it changes the model contract and only applies on the tool path.
NARRATIVE_TYPED_VERIFY = os.environ.get('NARRATIVE_TYPED_VERIFY', 'false').lower() == 'true'

# Methodology RAG. Embeddings come from Voyage AI (Anthropic has no embeddings
# API); retrieval degrades to empty results when no key is configured.
VOYAGE_API_KEY = os.environ.get('VOYAGE_API_KEY', '')
EMBED_MODEL = os.environ.get('EMBED_MODEL', 'voyage-3.5-lite')
VECTOR_DIM = 1024  # voyage-3.5-lite default output dimension; must match the model field
RAG_ENABLED = bool(VOYAGE_API_KEY)

# --- DRF ---

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}
